/**
 * This class is used to manage the population of the simulation.
 * It is responsible for creating the population, and for managing the population.
 */
public class PopulationManager {

    /**
     * Main method to run the simulation.
     * @param args arguments of the program
     */
    public static void main(String[] args) {

        int[][]         possibleLitters = { { 4, 5 }, { 5, 30 }, { 6, 30 }, { 7, 30 }, { 8, 5 } }; // Possible litter probas for each amount litter
        int             yearsSimulation = 10;                                                      // Amount years to simulate
        MersenneTwister random          = new MersenneTwister();                                   // Random number generator

        // Seed the random number generator
        random.setSeed(123456789);

        // If you want to change the sequence generated by Mersenne Twister
        // random.setSeed(985672121);

        // To evaluate just a population with i females and k males uncomment the 4 lines bellow
        /*
        Population rabbitPopulation = new Population(5, 5, 3,6,50,4,8,60,35,10,10,possibleLitters, random);


        for (int i = 0 ; i < yearsSimulation * 12 ; i++) {
            rabbitPopulation.evolution();
            rabbitPopulation.detailsDisplay(0);
        }
        */

        // To evaluate n population with i females and k males uncomment the 2 lines bellow
        EvaluatePopulation evalPop = new EvaluatePopulation(yearsSimulation, 50,10, 10, possibleLitters, random);
        evalPop.simulationPop();


    }

}