import java.sql.SQLOutput;

public class PopulationManager {

    public static void main(String[] args) {

        int[][] possibleLitters = { { 4, 5 }, { 5, 30 }, { 6, 30 }, { 7, 30 }, { 8, 5 } };
        int     yearsSimulation = 10;

        MersenneTwister random = new MersenneTwister();

        random.setSeed(123456789);

        // If you want to change the sequence generated by Mersenne Twister
        //random.setSeed(985672121);

        // To evaluate just a population with i females and k males uncomment the 4 lines bellow
        /*
        Population rabbitPopulation = new Population(5, 5, 3,6,50,4,8,60,35,10,10,possibleLitters, random);


        for (int i = 0 ; i < yearsSimulation * 12 ; i++) {
            rabbitPopulation.evolution();
            rabbitPopulation.detailsDisplay(0);
        }
        */

        // To evaluate n population with i females and k males uncomment the 2 lines bellow
        EvaluatePopulation evalPop = new EvaluatePopulation(1, 50,10, 10,possibleLitters, random);
        evalPop.simulationPop();





    }

}
